language: node_js
sudo: enabled
before_install:
- sudo apt-get -qq update
- nvm install v8.9.1
- nvm use v8.9.1
install:
- npm i
script:
# - yarn run test
- npm run build:gh
notifications:
  slack: dazedbear:lg4AOFwPUo1ialwVVkqgZ1J1